mkaurball: reverse logic to determine copy v. generate
The logic was the wrong way around, meaning that if srcinfo_path was not
set (default), the script tried to copy it into the tarball directory,
causing the script to fail. If it was set, then the script created a new
.AURINFO anyway.

diff --git a/mkaurball.in b/mkaurball.in
--- a/mkaurball.in
+++ b/mkaurball.in
@@ -53,12 +53,12 @@ mkaurball() {
   fi
 
   if [[ $srcinfo_path ]]; then
-    if ! srcinfo_create >"$tmpdir/$tarball_basename/.AURINFO"; then
-      die 'Failed to write .AURINFO'
-    fi
-  else
     if ! cp "$srcinfo_path" "$tmpdir/$tarball_basename/.AURINFO"; then
       die 'Failed to add %s to tarball' "$srcinfo_path"
+    fi
+  else
+    if ! srcinfo_create >"$tmpdir/$tarball_basename/.AURINFO"; then
+      die 'Failed to write .AURINFO'
     fi
   fi
 
